survey_kws:
  name: DECADE

gal_kws:
  type: exp
  gal_mag: custom
  gal_source: desdf
  
  size_min: 0.01
  size_max: 10.0
  q_min: 0.1
  q_max: 1.0
  mag_min: -30
  mag_max: 25.5
  
  n_grid: 120

  truth_type: grid

  circular: False

  extinction: True

files:
  save_meds: False
  clean_tmpdir: False

star_kws:
  stars: False
  star_source: lsst_sim
  f_bin: 0.4
  star_mag: custom
  upscale: 1
  
  mag_min: -30
  mag_max: 26
     
psf_kws:
  type: psfex_deconvolved

true_detection:
  box_size: 32
